### ISSUE TITLE
wrong directory structure

### ISSUE THREAD

**Issue by kklepper** [bojanz/musicbox#2]
git clone https://github.com/bojanz/musicbox.git

results in

.git
app
src
web
.gitignore
composer.json
composer.lock
LICENSE
README.md

consequently 

Warning: require_once(J:\www\musicbox\web/../vendor/autoload.php): failed to open stream: 

Copied vendor from silex-skeleton

Fatal error: Class 'Doctrine\DBAL\Configuration' not found in J:\www\musicbox\vendor\silex\silex\src\Silex\Provider\DoctrineServiceProvider.php 

What now?

**Comment by bojanz** [comment]
Vendor is created by composer when you do "composer install", like with any project that has a composer.json
